language: node_js
node_js:
  - "stable"
env:
  CODECLIMATE_REPO_TOKEN: 0a05bdccb231afa868698d741b6e4c5fcd161bebab035eade290121ddca87bfd
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master