version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: yarn test
      - run: yarn regression
      - run: yarn add -D codeclimate-test-reporter
      - run: yarn codeclimate-test-reporter < 'coverage/lcov.info'
      - run: GIT_USER=docusaurus-bot USE_SSH=true cd website && yarn && yarn run publish-gh-pages
