version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: yarn build
      - run: yarn screenshot
      - run: yarn regression

  deployment:
    production:
      branch: master
      commands:
        - git config --global user.name $USERNAME
        - git config --global user.email $EMAIL
        - npm run build
        - |
          cat <<EOF > ./public/circle.yml
          general:
            branches:
              ignore:
                - gh-pages
          EOF
        - npm run publish