version: 2

base_image: &base_image
  image: circleci/node:10.13-browsers

build_image: &build_image
  docker:
    - <<: *base_image
  working_directory: ~/repo

save_cache: &save_cache
  key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
  paths:
    - ~/.npm/_cacache

restore_cache: &restore_cache
  keys:
    - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
    - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}

jobs:
  upload_lock:
    <<: *build_image

    steps:
      - checkout
      - run: npx --package greenkeeper-lockfile@2 greenkeeper-lockfile-upload

workflows:
  version: 2
  exec:
    jobs:
      - upload_lock
